// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernHotel.Infrastructure.Data;

#nullable disable

namespace ModernHotel.Infrastructure.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260723195626_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModernHotel.Core.Entities.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Oak Street, New York, NY",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.mitchell@email.com",
                            FirstName = "James",
                            LastName = "Mitchell",
                            Nationality = "American",
                            Phone = "+1-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Storgatan 5, Stockholm",
                            CreatedAt = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sofia.andersson@email.com",
                            FirstName = "Sofia",
                            LastName = "Andersson",
                            Nationality = "Swedish",
                            Phone = "+46-70-123456"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Calle Mayor 42, Madrid",
                            CreatedAt = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carlos.rodriguez@email.com",
                            FirstName = "Carlos",
                            LastName = "Rodriguez",
                            Nationality = "Spanish",
                            Phone = "+34-91-234567"
                        },
                        new
                        {
                            Id = 4,
                            Address = "1-2-3 Shinjuku, Tokyo",
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yuki.tanaka@email.com",
                            FirstName = "Yuki",
                            LastName = "Tanaka",
                            Nationality = "Japanese",
                            Phone = "+81-3-12345678"
                        },
                        new
                        {
                            Id = 5,
                            Address = "15 Baker Street, London",
                            CreatedAt = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.thompson@email.com",
                            FirstName = "Emma",
                            LastName = "Thompson",
                            Nationality = "British",
                            Phone = "+44-20-987654"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Via Roma 88, Milan",
                            CreatedAt = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marco.ferrari@email.com",
                            FirstName = "Marco",
                            LastName = "Ferrari",
                            Nationality = "Italian",
                            Phone = "+39-02-345678"
                        },
                        new
                        {
                            Id = 7,
                            Address = "DIFC Tower, Dubai",
                            CreatedAt = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aisha.khalil@email.com",
                            FirstName = "Aisha",
                            LastName = "Khalil",
                            Nationality = "Emirati",
                            Phone = "+971-50-123456"
                        },
                        new
                        {
                            Id = 8,
                            Address = "500 Sand Hill Rd, Palo Alto",
                            CreatedAt = new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.chen@email.com",
                            FirstName = "David",
                            LastName = "Chen",
                            Nationality = "American",
                            Phone = "+1-650-555-0199"
                        },
                        new
                        {
                            Id = 9,
                            Address = "12 Rue de Rivoli, Paris",
                            CreatedAt = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marie.dubois@email.com",
                            FirstName = "Marie",
                            LastName = "Dubois",
                            Nationality = "French",
                            Phone = "+33-1-23456789"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Av Paulista 1500, São Paulo",
                            CreatedAt = new DateTime(2024, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas.oliveira@email.com",
                            FirstName = "Lucas",
                            LastName = "Oliveira",
                            Nationality = "Brazilian",
                            Phone = "+55-11-98765432"
                        },
                        new
                        {
                            Id = 11,
                            Address = "MG Road, Bangalore",
                            CreatedAt = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya.sharma@email.com",
                            FirstName = "Priya",
                            LastName = "Sharma",
                            Nationality = "Indian",
                            Phone = "+91-98765-43210"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Tverskaya 10, Moscow",
                            CreatedAt = new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.petrov@email.com",
                            FirstName = "Alexander",
                            LastName = "Petrov",
                            Nationality = "Russian",
                            Phone = "+7-495-123456"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Kurfürstendamm 100, Berlin",
                            CreatedAt = new DateTime(2024, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hannah.mueller@email.com",
                            FirstName = "Hannah",
                            LastName = "Müller",
                            Nationality = "German",
                            Phone = "+49-30-123456"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Tahrir Square 5, Cairo",
                            CreatedAt = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.hassan@email.com",
                            FirstName = "Omar",
                            LastName = "Hassan",
                            Nationality = "Egyptian",
                            Phone = "+20-2-12345678"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Piazza Navona 3, Rome",
                            CreatedAt = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabella.rossi@email.com",
                            FirstName = "Isabella",
                            LastName = "Rossi",
                            Nationality = "Italian",
                            Phone = "+39-06-456789"
                        });
                });

            modelBuilder.Entity("ModernHotel.Core.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualCheckIn = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualCheckOut = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            RoomId = 3,
                            Status = 4,
                            TotalAmount = 597.00m
                        },
                        new
                        {
                            Id = 2,
                            ActualCheckIn = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualCheckOut = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adults = 1,
                            CheckInDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 2,
                            RoomId = 6,
                            Status = 4,
                            TotalAmount = 1047.00m
                        },
                        new
                        {
                            Id = 3,
                            ActualCheckIn = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualCheckOut = new DateTime(2025, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adults = 1,
                            CheckInDate = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 5,
                            RoomId = 1,
                            Status = 4,
                            TotalAmount = 258.00m
                        },
                        new
                        {
                            Id = 4,
                            ActualCheckIn = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualCheckOut = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 1,
                            CreatedAt = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 9,
                            RoomId = 9,
                            Status = 4,
                            TotalAmount = 2397.00m
                        },
                        new
                        {
                            Id = 5,
                            ActualCheckIn = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 2,
                            CreatedAt = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 3,
                            RoomId = 4,
                            Status = 3,
                            TotalAmount = 916.00m
                        },
                        new
                        {
                            Id = 6,
                            ActualCheckIn = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 4,
                            RoomId = 7,
                            Status = 3,
                            TotalAmount = 1796.00m
                        },
                        new
                        {
                            Id = 7,
                            ActualCheckIn = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 2,
                            CreatedAt = new DateTime(2025, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 7,
                            RoomId = 10,
                            Status = 3,
                            TotalAmount = 3996.00m
                        },
                        new
                        {
                            Id = 8,
                            ActualCheckIn = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Adults = 1,
                            CheckInDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 8,
                            RoomId = 5,
                            Status = 3,
                            TotalAmount = 796.00m
                        },
                        new
                        {
                            Id = 9,
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 6,
                            RoomId = 8,
                            Status = 2,
                            TotalAmount = 1497.00m
                        },
                        new
                        {
                            Id = 10,
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 1,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 11,
                            RoomId = 2,
                            Status = 2,
                            TotalAmount = 298.00m
                        },
                        new
                        {
                            Id = 11,
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 10,
                            RoomId = 6,
                            Status = 2,
                            TotalAmount = 1047.00m
                        },
                        new
                        {
                            Id = 12,
                            Adults = 1,
                            CheckInDate = new DateTime(2025, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 12,
                            RoomId = 3,
                            Status = 2,
                            TotalAmount = 597.00m
                        },
                        new
                        {
                            Id = 13,
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 13,
                            RoomId = 9,
                            Status = 2,
                            TotalAmount = 3196.00m
                        },
                        new
                        {
                            Id = 14,
                            Adults = 1,
                            CheckInDate = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 14,
                            RoomId = 1,
                            Status = 1,
                            TotalAmount = 387.00m
                        },
                        new
                        {
                            Id = 15,
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 15,
                            RoomId = 7,
                            Status = 1,
                            TotalAmount = 1796.00m
                        },
                        new
                        {
                            Id = 16,
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            RoomId = 2,
                            Status = 5,
                            TotalAmount = 447.00m
                        },
                        new
                        {
                            Id = 17,
                            Adults = 1,
                            CheckInDate = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 5,
                            RoomId = 8,
                            Status = 5,
                            TotalAmount = 1497.00m
                        },
                        new
                        {
                            Id = 18,
                            Adults = 1,
                            CheckInDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 12,
                            RoomId = 5,
                            Status = 6,
                            TotalAmount = 398.00m
                        },
                        new
                        {
                            Id = 19,
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 2,
                            CreatedAt = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 2,
                            RoomId = 4,
                            Status = 2,
                            TotalAmount = 687.00m
                        },
                        new
                        {
                            Id = 20,
                            Adults = 2,
                            CheckInDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            CreatedAt = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 8,
                            RoomId = 10,
                            Status = 1,
                            TotalAmount = 4995.00m
                        });
                });

            modelBuilder.Entity("ModernHotel.Core.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedCount = 1,
                            Description = "Cozy standard room with garden view",
                            Floor = 1,
                            IsActive = true,
                            MaxOccupancy = 2,
                            RatePerNight = 129.00m,
                            RoomNumber = "101",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            BedCount = 2,
                            Description = "Spacious standard double room",
                            Floor = 1,
                            IsActive = true,
                            MaxOccupancy = 4,
                            RatePerNight = 149.00m,
                            RoomNumber = "102",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            BedCount = 1,
                            Description = "Deluxe room with city view",
                            Floor = 2,
                            IsActive = true,
                            MaxOccupancy = 2,
                            RatePerNight = 199.00m,
                            RoomNumber = "201",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            BedCount = 2,
                            Description = "Deluxe double room with balcony",
                            Floor = 2,
                            IsActive = true,
                            MaxOccupancy = 4,
                            RatePerNight = 229.00m,
                            RoomNumber = "202",
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            BedCount = 1,
                            Description = "Deluxe room with pool view",
                            Floor = 2,
                            IsActive = true,
                            MaxOccupancy = 2,
                            RatePerNight = 199.00m,
                            RoomNumber = "203",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            BedCount = 1,
                            Description = "Junior suite with separate living area",
                            Floor = 3,
                            IsActive = true,
                            MaxOccupancy = 3,
                            RatePerNight = 349.00m,
                            RoomNumber = "301",
                            Type = 3
                        },
                        new
                        {
                            Id = 7,
                            BedCount = 2,
                            Description = "Executive suite with panoramic view",
                            Floor = 3,
                            IsActive = true,
                            MaxOccupancy = 4,
                            RatePerNight = 449.00m,
                            RoomNumber = "302",
                            Type = 3
                        },
                        new
                        {
                            Id = 8,
                            BedCount = 2,
                            Description = "Presidential suite with private terrace",
                            Floor = 3,
                            IsActive = true,
                            MaxOccupancy = 4,
                            RatePerNight = 499.00m,
                            RoomNumber = "303",
                            Type = 3
                        },
                        new
                        {
                            Id = 9,
                            BedCount = 2,
                            Description = "Penthouse with full-floor panoramic views",
                            Floor = 4,
                            IsActive = true,
                            MaxOccupancy = 4,
                            RatePerNight = 799.00m,
                            RoomNumber = "401",
                            Type = 4
                        },
                        new
                        {
                            Id = 10,
                            BedCount = 3,
                            Description = "Grand penthouse with private pool access",
                            Floor = 4,
                            IsActive = true,
                            MaxOccupancy = 6,
                            RatePerNight = 999.00m,
                            RoomNumber = "402",
                            Type = 4
                        });
                });

            modelBuilder.Entity("ModernHotel.Core.Entities.Reservation", b =>
                {
                    b.HasOne("ModernHotel.Core.Entities.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModernHotel.Core.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ModernHotel.Core.Entities.Guest", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ModernHotel.Core.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
